### ISSUE TITLE
Trying to convert Float8_e4m3fn to the MPS backend but it does not have support for that dtype.

### ISSUE THREAD

**Issue by ZeeMenng** [MinusZoneAI/ComfyUI-CogVideoX-MZ#19]
换了各种weight_type都不行。

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/a7698ce0-50db-4755-a003-2c94838d3b58">

**Comment by wailovet** [comment]
关掉fp8_fast_mode可以吗

**Comment by ZeeMenng** [comment]
不行，关掉后显示RuntimeError: unsupported scalarType
<img width="1518" alt="image" src="https://github.com/user-attachments/assets/0b1fa88c-d163-46a3-83bb-03d7af5b6ab0">
got prompt
transformer type: 5b
GGUF: False
model weight dtype: torch.float8_e4m3fn manual cast dtype: torch.float16
Encoded latents shape: torch.Size([1, 1, 16, 60, 90])
/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
Requested to load SD3ClipModel_
Loading 1 new model
loaded completely 0.0 4541.693359375 True
!!! Exception during processing !!! unsupported scalarType
Traceback (most recent call last):
  File "/Users/ZeeMenng/Project/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ZeeMenng/Project/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ZeeMenng/Project/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/Users/ZeeMenng/Project/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ZeeMenng/Project/ComfyUI/custom_nodes/ComfyUI-CogVideoXWrapper/nodes.py", line 841, in process
    autocast_context = torch.autocast(mm.get_autocast_device(device)) if autocastcondition else nullcontext()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/torch/amp/autocast_mode.py", line 229, in __init__
    dtype = torch.get_autocast_dtype(device_type)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: unsupported scalarType

**Comment by wailovet** [comment]
更新一下ComfyUI-CogVideoXWrapper试试

**Comment by ZeeMenng** [comment]
全都升级过了，一样的错误，试了各种办法不行，很奇怪。

我的是M1 Pro，Python我用3.12和3.11两个版本分别作了尝试，都不行。不知道哪个依赖包版本有问题，还是怎样的。


<img width="1328" alt="image" src="https://github.com/user-attachments/assets/5bfeece5-b869-4049-b34a-8b07e8116f7e">
<img width="519" alt="image" src="https://github.com/user-attachments/assets/2c5781bb-b952-437b-b3a4-3ef2e112338f">
<img width="1208" alt="image" src="https://github.com/user-attachments/assets/8c4313ca-dcf9-42da-a151-bf70c37b251c">

**Comment by wailovet** [comment]
目前看起来支持应该有些问题, 可以看 https://github.com/kijai/ComfyUI-CogVideoXWrapper/issues/59

**Comment by LONGG1126** [comment]
你解决这个问题了吗

**Comment by lvboy1** [comment]
我是m1max运行flux模型的时候出现这个问题，解决方式是打开comfyui的时候用cpu运行
python main.py --force-fp16 --use-split-cross-attention --cpu
切换cpu运行以后可以完整运行流程，不过速度很慢很慢=。=
感觉是mac支持的问题，要是想快只能换电脑
