### ISSUE TITLE
CogVideoXPipeline.__call__() got an unexpected keyword argument 'tora'

### ISSUE THREAD

**Issue by TRONBFFL** [MinusZoneAI/ComfyUI-CogVideoX-MZ#27]
Keep getting this error.  Welcome help!
<img width="553" alt="image" src="https://github.com/user-attachments/assets/4592721f-e03b-4b66-8b6e-6d64766b4f23">

**Comment by TRONBFFL** [comment]
The config attributes {'snr_shift_scale': 1.0} were passed to EulerDiscreteScheduler, but are not expected and will be ignored. Please verify your scheduler_config.json configuration file.
!!! Exception during processing !!! CogVideoXPipeline.__call__() got an unexpected keyword argument 'tora'
Traceback (most recent call last):
  File "C:\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "C:\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\nodes.py", line 1319, in process
    latents = pipeline["pipe"](
  File "C:\ComfyUI\venv\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
TypeError: CogVideoXPipeline.__call__() got an unexpected keyword argument 'tora'

**Comment by TRONBFFL** [comment]
Tried updating to accelerate-1.0.1 but no help

**Comment by whois206** [comment]
# ComfyUI Error Report
## Error Details
- **Node Type:** CogVideoSampler
- **Exception Type:** TypeError
- **Exception Message:** CogVideoXPipeline.__call__() got an unexpected keyword argument 'tora'
## Stack Trace
```
  File "D:\ComfyUI\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "D:\ComfyUI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\nodes.py", line 1373, in process
    latents = pipeline["pipe"](
              ^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^

```
## System Information
- **ComfyUI Version:** v0.2.5
- **Arguments:** ComfyUI\main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.4.0+cu118
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4060 Ti : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 17175150592
  - **VRAM Free:** 12310416320
  - **Torch VRAM Total:** 3690987520
  - **Torch VRAM Free:** 80874432

**Comment by wailovet** [comment]
Try again after updating the current repository.

**Comment by dkqjhoifh** [comment]
> 尝试更新到 accelerate-1.0.1 但没有帮助

me too
