### ISSUE TITLE
Unsupported TypeMeta in ATen: nullptr (uninitialized) (please report this error)

### ISSUE THREAD

**Issue by BertWang** [MinusZoneAI/ComfyUI-CogVideoX-MZ#3]
有請解惑

# ComfyUI Error Report
## Error Details
- **Node Type:** CogVideoSampler
- **Exception Type:** RuntimeError
- **Exception Message:** Unsupported TypeMeta in ATen: nullptr (uninitialized) (please report this error)
## Stack Trace
```
  File "E:\AI\ComfyUI-aki-v1.3\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "E:\AI\ComfyUI-aki-v1.3\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "E:\AI\ComfyUI-aki-v1.3\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "E:\AI\ComfyUI-aki-v1.3\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "E:\AI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-CogVideoXWrapper\nodes.py", line 296, in process
    latents = pipeline["pipe"](

  File "E:\AI\ComfyUI-aki-v1.3\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)

  File "E:\AI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-CogVideoX-MZ\pipeline_cogvideox.py", line 545, in __call__
    latent_model_input = torch.cat([latents] * 2) if do_classifier_free_guidance else latents

```
## System Information
- **ComfyUI Version:** v0.1.3-24-gb643eae
- **Arguments:** E:\AI\ComfyUI-aki-v1.3\main.py --auto-launch --dont-upcast-attention --preview-method auto --disable-smart-memory --disable-cuda-malloc
- **OS:** nt
- **Python Version:** 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.1.2+cu118
## Devices

**Comment by wailovet** [comment]
截个流的图看看

**Comment by s3219521aa** [comment]
我遇见了相同的问题，使用的就是该GitHub项目提供的工作流

# ComfyUI Error Report
## Error Details
- **Node Type:** CogVideoSampler
- **Exception Type:** RuntimeError
- **Exception Message:** Unsupported TypeMeta in ATen: nullptr (uninitialized) (please report this error)
## Stack Trace
```
  File "D:\ComfyUI-aki-v1.3\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "D:\ComfyUI-aki-v1.3\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "D:\ComfyUI-aki-v1.3\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "D:\ComfyUI-aki-v1.3\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-CogVideoXWrapper\nodes.py", line 321, in process
    latents = pipeline["pipe"](

  File "D:\ComfyUI-aki-v1.3\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)

  File "D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-CogVideoX-MZ\pipeline_cogvideox.py", line 582, in __call__
    latent_model_input = torch.cat([latents] * 2) if do_classifier_free_guidance else latents

```
## System Information
- **ComfyUI Version:** v0.2.1-1-gf067ad1
- **Arguments:** D:\ComfyUI-aki-v1.3\main.py --auto-launch --preview-method auto --disable-cuda-malloc
- **OS:** nt
- **Python Version:** 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.1.2+cu118
## Devices

- **Name:** cuda:0 Quadro GV100 : native
  - **Type:** cuda
  - **VRAM Total:** 34359148544
  - **VRAM Free:** 26391009792
  - **Torch VRAM Total:** 7358906368
  - **Torch VRAM Free:** 808901120

## Logs
```
2024-09-05 17:04:51,174 - root - INFO - Total VRAM 32767 MB, total RAM 130665 MB
2024-09-05 17:04:51,174 - root - INFO - pytorch version: 2.1.2+cu118
2024-09-05 17:04:53,597 - root - INFO - xformers version: 0.0.23.post1+cu118
2024-09-05 17:04:53,597 - root - INFO - Set vram state to: NORMAL_VRAM
2024-09-05 17:04:53,597 - root - INFO - Device: cuda:0 Quadro GV100 : native
2024-09-05 17:04:56,272 - root - INFO - Using xformers cross attention
2024-09-05 17:04:57,719 - root - INFO - [Prompt Server] web root: D:\ComfyUI-aki-v1.3\web
2024-09-05 17:06:01,930 - root - WARNING - Traceback (most recent call last):
  File "D:\ComfyUI-aki-v1.3\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI-aki-v1.3\custom_nodes\efficiency-nodes-comfyui\__init__.py", line 9, in <module>
    from  .efficiency_nodes import NODE_CLASS_MAPPINGS
  File "D:\ComfyUI-aki-v1.3\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 46, in <module>
    from .py import smZ_cfg_denoiser
  File "D:\ComfyUI-aki-v1.3\custom_nodes\efficiency-nodes-comfyui\py\smZ_cfg_denoiser.py", line 7, in <module>
    from comfy.samplers import KSampler, KSamplerX0Inpaint, wrap_model
ImportError: cannot import name 'wrap_model' from 'comfy.samplers' (D:\ComfyUI-aki-v1.3\comfy\samplers.py)

2024-09-05 17:06:01,930 - root - WARNING - Cannot import D:\ComfyUI-aki-v1.3\custom_nodes\efficiency-nodes-comfyui module for custom nodes: cannot import name 'wrap_model' from 'comfy.samplers' (D:\ComfyUI-aki-v1.3\comfy\samplers.py)
2024-09-05 17:06:15,459 - root - INFO - 
Import times for custom nodes:
2024-09-05 17:06:15,459 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.3\custom_nodes\AIGODLIKE-ComfyUI-Translation
2024-09-05 17:06:15,459 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.3\custom_nodes\ControlNet-LLLite-ComfyUI
2024-09-05 17:06:15,459 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.3\custom_nodes\websocket_image_save.py
2024-09-05 17:06:15,459 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.3\custom_nodes\extended-saveimage-comfyui
2024-09-05 17:06:15,459 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.3\custom_nodes\FreeU_Advanced
2024-09-05 17:06:15,459 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-CogVideoXWrapper
2024-09-05 17:06:15,459 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_IPAdapter_plus
2024-09-05 17:06:15,459 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_TiledKSampler
2024-09-05 17:06:15,459 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.3\custom_nodes\stability-ComfyUI-nodes
2024-09-05 17:06:15,459 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_experiments
2024-09-05 17:06:15,459 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.3\custom_nodes\PowerNoiseSuite
2024-09-05 17:06:15,459 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.3\custom_nodes\images-grid-comfy-plugin
2024-09-05 17:06:15,459 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_UltimateSDUpscale
2024-09-05 17:06:15,459 - root - INFO -    0.0 seconds (IMPORT FAILED): D:\ComfyUI-aki-v1.3\custom_nodes\efficiency-nodes-comfyui
2024-09-05 17:06:15,459 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Advanced-ControlNet
2024-09-05 17:06:15,459 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.3\custom_nodes\save-image-extended-comfyui
2024-09-05 17:06:15,459 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.3\custom_nodes\Derfuu_ComfyUI_ModdedNodes
2024-09-05 17:06:15,459 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-AnimateDiff-Evolved
2024-09-05 17:06:15,459 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.3\custom_nodes\x-flux-comfyui
2024-09-05 17:06:15,459 - root - INFO -    0.1 seconds: D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-WD14-Tagger
2024-09-05 17:06:15,459 - root - INFO -    0.1 seconds: D:\ComfyUI-aki-v1.3\custom_nodes\comfyui-workspace-manager
2024-09-05 17:06:15,459 - root - INFO -    0.1 seconds: D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Marigold
2024-09-05 17:06:15,459 - root - INFO -    0.1 seconds: D:\ComfyUI-aki-v1.3\custom_nodes\rgthree-comfy
2024-09-05 17:06:15,459 - root - INFO -    0.1 seconds: D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_essentials
2024-09-05 17:06:15,459 - root - INFO -    0.1 seconds: D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Custom-Scripts
2024-09-05 17:06:15,459 - root - INFO -    0.1 seconds: D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_Comfyroll_CustomNodes
2024-09-05 17:06:15,459 - root - INFO -    0.2 seconds: D:\ComfyUI-aki-v1.3\custom_nodes\comfyui_controlnet_aux
2024-09-05 17:06:15,459 - root - INFO -    0.2 seconds: D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Inspire-Pack
2024-09-05 17:06:15,459 - root - INFO -    0.3 seconds: D:\ComfyUI-aki-v1.3\custom_nodes\comfyui-tensorops
2024-09-05 17:06:15,459 - root - INFO -    0.3 seconds: D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-IF_AI_tools
2024-09-05 17:06:15,459 - root - INFO -    0.7 seconds: D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_FizzNodes
2024-09-05 17:06:15,459 - root - INFO -    0.8 seconds: D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-CogVideoX-MZ
2024-09-05 17:06:15,459 - root - INFO -    0.8 seconds: D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Manager
2024-09-05 17:06:15,459 - root - INFO -    1.1 seconds: D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-VideoHelperSuite
2024-09-05 17:06:15,459 - root - INFO -    1.2 seconds: D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Florence2
2024-09-05 17:06:15,459 - root - INFO -    2.0 seconds: D:\ComfyUI-aki-v1.3\custom_nodes\comfy_mtb
2024-09-05 17:06:15,459 - root - INFO -    3.1 seconds: D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_LayerStyle
2024-09-05 17:06:15,459 - root - INFO -    6.7 seconds: D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Impact-Pack
2024-09-05 17:06:15,459 - root - INFO -   13.3 seconds: D:\ComfyUI-aki-v1.3\custom_nodes\was-node-suite-comfyui
2024-09-05 17:06:15,463 - root - INFO -   13.8 seconds: D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Crystools
2024-09-05 17:06:15,463 - root - INFO -   30.2 seconds: D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_Custom_Nodes_AlekPet
2024-09-05 17:06:15,463 - root - INFO - 
2024-09-05 17:06:15,480 - root - INFO - Starting server

2024-09-05 17:06:15,480 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-09-05 17:06:18,432 - root - ERROR - [ERROR] An error occurred while retrieving information for the 'IF_ChatPrompt' node.
2024-09-05 17:06:18,432 - root - ERROR - Traceback (most recent call last):
  File "D:\ComfyUI-aki-v1.3\server.py", line 486, in get_object_info
    out[x] = node_info(x)
  File "D:\ComfyUI-aki-v1.3\server.py", line 454, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 109, in INPUT_TYPES
    node = cls()
  File "D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 53, in __init__
    self.agent_tools = self.load_agent_tools()
  File "D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-IF_AI_tools\IFChatPromptNode.py", line 78, in load_agent_tools
    for filename in os.listdir(self.agents_dir):
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'D:\\ComfyUI-aki-v1.3\\input\\IF_AI\\presets\\agents'

2024-09-06 08:08:38,113 - root - INFO - got prompt
2024-09-06 08:11:57,833 - root - INFO - Requested to load SD3ClipModel_
2024-09-06 08:11:57,833 - root - INFO - Loading 1 new model
2024-09-06 08:11:57,841 - root - INFO - loaded completely 0.0 4541.693359375 True
2024-09-06 08:12:06,048 - root - ERROR - !!! Exception during processing !!! Unsupported TypeMeta in ATen: nullptr (uninitialized) (please report this error)
2024-09-06 08:12:06,148 - root - ERROR - Traceback (most recent call last):
  File "D:\ComfyUI-aki-v1.3\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\ComfyUI-aki-v1.3\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\ComfyUI-aki-v1.3\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI-aki-v1.3\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-CogVideoXWrapper\nodes.py", line 321, in process
    latents = pipeline["pipe"](
  File "D:\ComfyUI-aki-v1.3\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-CogVideoX-MZ\pipeline_cogvideox.py", line 582, in __call__
    latent_model_input = torch.cat([latents] * 2) if do_classifier_free_guidance else latents
RuntimeError: Unsupported TypeMeta in ATen: nullptr (uninitialized) (please report this error)

2024-09-06 08:12:06,150 - root - INFO - Prompt executed in 207.90 seconds
2024-09-06 08:12:40,889 - root - INFO - got prompt
2024-09-06 08:12:41,076 - root - ERROR - !!! Exception during processing !!! Unsupported TypeMeta in ATen: nullptr (uninitialized) (please report this error)
2024-09-06 08:12:41,076 - root - ERROR - Traceback (most recent call last):
  File "D:\ComfyUI-aki-v1.3\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\ComfyUI-aki-v1.3\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\ComfyUI-aki-v1.3\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI-aki-v1.3\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-CogVideoXWrapper\nodes.py", line 321, in process
    latents = pipeline["pipe"](
  File "D:\ComfyUI-aki-v1.3\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-CogVideoX-MZ\pipeline_cogvideox.py", line 582, in __call__
    latent_model_input = torch.cat([latents] * 2) if do_classifier_free_guidance else latents
RuntimeError: Unsupported TypeMeta in ATen: nullptr (uninitialized) (please report this error)

2024-09-06 08:12:41,076 - root - INFO - Prompt executed in 0.12 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":39,"last_link_id":71,"nodes":[{"id":31,"type":"CogVideoTextEncode","pos":{"0":503,"1":521,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":465,"1":320},"flags":{},"order":3,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":56,"label":"CLIP"}],"outputs":[{"name":"conditioning","type":"CONDITIONING","links":[62],"slot_index":0,"shape":3,"label":"条件"}],"properties":{"Node name for S&R":"CogVideoTextEncode"},"widgets_values":[""]},{"id":30,"type":"CogVideoTextEncode","pos":{"0":500,"1":308,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":471.90142822265625,"1":168.08047485351562},"flags":{},"order":2,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":54,"label":"CLIP"}],"outputs":[{"name":"conditioning","type":"CONDITIONING","links":[61],"slot_index":0,"shape":3,"label":"条件"}],"properties":{"Node name for S&R":"CogVideoTextEncode"},"widgets_values":["The camera moves upwards, showing the back of a woman wearing a red gown standing on the roof. The building in the distance is smoking."]},{"id":33,"type":"VHS_VideoCombine","pos":{"0":1447,"1":162,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":[780,310],"flags":{},"order":6,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":59,"label":"图像"},{"name":"audio","type":"AUDIO","link":null,"label":"音频"},{"name":"meta_batch","type":"VHS_BatchManager","link":null,"label":"批次管理"},{"name":"vae","type":"VAE","link":null}],"outputs":[{"name":"Filenames","type":"VHS_FILENAMES","links":null,"shape":3,"label":"文件名"}],"properties":{"Node name for S&R":"VHS_VideoCombine"},"widgets_values":{"frame_rate":8,"loop_count":0,"filename_prefix":"CogVideoX5B","format":"video/h264-mp4","pix_fmt":"yuv420p","crf":19,"save_metadata":true,"pingpong":false,"save_output":true,"videopreview":{"hidden":false,"paused":false,"params":{"filename":"CogVideoX5B_00018.mp4","subfolder":"","type":"output","format":"video/h264-mp4","frame_rate":8},"muted":false}}},{"id":39,"type":"MZ_CogVideoXLoader","pos":{"0":151,"1":101,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":315,"1":178},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"cogvideo_pipe","type":"COGVIDEOPIPE","links":[71],"slot_index":0,"shape":3,"label":"cogvideo_pipe"}],"properties":{"Node name for S&R":"MZ_CogVideoXLoader"},"widgets_values":["CogVideoX_5b_fp8_4em.safetensors","CogVideoX-5b-VAE.safetensors","fp8_e4m3fn",true,0]},{"id":20,"type":"CLIPLoader","pos":{"0":16,"1":393,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":451.30548095703125,"1":82},"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"CLIP","type":"CLIP","links":[54,56],"slot_index":0,"shape":3,"label":"CLIP"}],"properties":{"Node name for S&R":"CLIPLoader"},"widgets_values":["t5xxl_fp8_e4m3fn.safetensors","sd3"]},{"id":34,"type":"CogVideoSampler","pos":{"0":1033,"1":280,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":315.8404846191406,"1":358},"flags":{},"order":4,"mode":0,"inputs":[{"name":"pipeline","type":"COGVIDEOPIPE","link":71,"label":"CogVideo"},{"name":"positive","type":"CONDITIONING","link":61,"label":"正面条件"},{"name":"negative","type":"CONDITIONING","link":62,"label":"负面条件"},{"name":"samples","type":"LATENT","link":null,"label":"Latent"}],"outputs":[{"name":"cogvideo_pipe","type":"COGVIDEOPIPE","links":[63],"shape":3,"label":"CogVideo"},{"name":"samples","type":"LATENT","links":[64],"shape":3,"label":"Latent"}],"properties":{"Node name for S&R":"CogVideoSampler"},"widgets_values":[480,720,49,50,6,806286757407563,"fixed","DPM",49,8,1]},{"id":11,"type":"CogVideoDecode","pos":{"0":1099,"1":741,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":[362.7203732064411,250.4926366243542],"flags":{},"order":5,"mode":0,"inputs":[{"name":"pipeline","type":"COGVIDEOPIPE","link":63,"label":"CogVideo"},{"name":"samples","type":"LATENT","link":64,"label":"Latent"}],"outputs":[{"name":"images","type":"IMAGE","links":[59],"slot_index":0,"shape":3,"label":"图像"}],"properties":{"Node name for S&R":"CogVideoDecode"},"widgets_values":[true,96,96,0.083,0.083,true]}],"links":[[54,20,0,30,0,"CLIP"],[56,20,0,31,0,"CLIP"],[59,11,0,33,0,"IMAGE"],[61,30,0,34,1,"CONDITIONING"],[62,31,0,34,2,"CONDITIONING"],[63,34,0,11,0,"COGVIDEOPIPE"],[64,34,1,11,1,"LATENT"],[71,39,0,34,0,"COGVIDEOPIPE"]],"groups":[],"config":{},"extra":{"ds":{"scale":0.8264462809917354,"offset":[-48.915708428242596,123.55669867312012]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here

**Comment by wailovet** [comment]
I found some clues about this problem in  https://github.com/pytorch/pytorch/issues/107256, maybe you can update pytorch to the latest version
